# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_prueba_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='jajajaja',
            field=models.CharField(default='', max_length=30),
        ),
    ]
