# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_prueba_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='ok',
        ),
    ]
