# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_remove_prueba_ok'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
