# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='estatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
