# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-14 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_marca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='estatus',
        ),
        migrations.DeleteModel(
            name='marca',
        ),
    ]
