# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-14 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_auto_20160614_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='caducidad',
        ),
    ]
