# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='estatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('Ac', 'Activo'), ('Des', 'Desactivo')], default='Ac', max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
