# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-20 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0019_delete_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='', max_length=200),
        ),
    ]
